### ISSUE TITLE
Logic Pro mono channels issue

### ISSUE THREAD

**Issue by hjfierro** [jerryuhoo/Fire#21]
First of all, your plugin is fantastic. I have been testing it and it is reaching the best ones. However, one major issue is that it doesn't work correctly on mono channels in Logic Pro. When I load a preset, made on a stereo channel, it crashes. Also if I turn on HQ mode.

**Comment by jerryuhoo** [comment]
Hi, could you provide your macOS version and your Logic Pro version? I think there are some bugs when the plugin deals with the mono channel mode, but it didn't crash on my environment.

**Comment by hjfierro** [comment]
Catalina 10.15.7
Logic Pro 10.6.3

**Comment by jerryuhoo** [comment]
Hi, I fixed the bug that HQ mode crashes Logic Pro, I made a release here: https://github.com/jerryuhoo/Fire/releases/tag/v0.9.6
I am not sure if I have fixed the stereo preset bug because it doesn't appear on my mac, but I've tried to find the possible cause and made some changes. Could you test it again and see if the bug is still there. Thanks a lot!
