### ISSUE TITLE
Plugin not loaded in Linux

### ISSUE THREAD

**Issue by Donmanouche** [jerryuhoo/Fire#26]
Hello,
The plugin cannot be loaded on my Linux system. It does not appear in the plugins list in bitwig and Carla says it failed to load the file as it could not find the VST main entry in the plugin library.

**Comment by jerryuhoo** [comment]
The linux version is auto-generated by release and I haven't done any test yet. But in your case, I guess, the path of VST3 is not the same as VST's. So I found an answer on reddit that said: "copy vst3 plugin to your vst3 path, which usually is a hidden folder in your home directly ~/.vst3. If this directory doesn't exist create it yourself."
https://www.reddit.com/r/linuxaudio/comments/pmxidr/how_do_i_load_vst3_plugins_in_bitwig/

**Comment by Donmanouche** [comment]
Thank you. The plugin was correctly copied in the .vst3 folder, hence the issue is not path related.

**Comment by Donmanouche** [comment]
I had copied onlu the .so file in the .vst3 folder. It works when I copy the entire Fire-Linux folder. Issue solved.
Looking forward testing 火 !

**Comment by jerryuhoo** [comment]
Cool! I recommend you download the [latest version 0.9.8](https://github.com/jerryuhoo/Fire/releases/tag/v0.9.8) since the previous versions had HQ mode bugs. 

Also, to those who are using the plugin for production, I am working on a new version so that each bypass button for width control and compressor can work separately for each band. Be careful that those bypass buttons of previous presets will be set to disable regardless of whether you turned them on. And it will be released in a few days.

**Comment by jerryuhoo** [comment]
If you have any questions, you are welcome to reopen this issue anytime.
