### ISSUE TITLE
[Feature Request] take out the ON/OFF buttons -less clicking is more

### ISSUE THREAD

**Issue by cxbignekoc** [jerryuhoo/Fire#31]
Hi

why can not ZERO equal to OFF?

thank you, great plugin !

**Comment by jerryuhoo** [comment]
Hi, I decide not to add this feature because once you turned the "mix knob" to 0, the on/off button will be shut down and you cannot drag the mix knob anymore. Also, I have to keep on/off buttons to compare the distortion effect. Other plugins such as Ozone and Saturn all have this feature. Feel free to reopen this issue if you have any other questions! 😃
