### ISSUE TITLE
Output levelling issue

### ISSUE THREAD

**Issue by atroubledcarrot** [jerryuhoo/Fire#55]
Was trying to gain stage my drumbus properly by manually setting the output (with the autolevelling (L button) off) but it would not accurately drop the output level or something of the sort. So I'd be doing comparisons and trying to do quick exports to send out but then the next moment my drumbus level drops significantly after reactivating Fire.

**Comment by Abdusalyamov** [comment]
Yeah, I got the same issue, I wonder if it's even output level problem, I wonder if It changes the sound even if there's no effect applied

**Comment by jerryuhoo** [comment]
Hi, sorry for the late reply. 

I just want to confirm the issue. Are you saying that adjusting the output does not accurately adjust the volume? Is it in  "Band effect" or "Global effect"? Does this happen randomly or every time? Please make sure the mix is set to 1 because the mix is applied after the output. And for arctan distortion, the function itself reduces some volume. If this issue occurs infrequently, could you provide the steps to reproduce it? I tested it on my end, but it seems I was unable to trigger this bug. 

Thanks!

**Comment by Abdusalyamov** [comment]
Hi
It's in the global effect, In order to get the same volume I have to make
output 6db, After I figured that out It doesn't bother me anymore.
I checked it again, it's because of acrtan distortion, yep, it makes sound
quieter, other kinds of distortion do not affect the loudness.

Thank you for the reply

чт, 23 мая 2024 г. в 07:19, Yifeng (Jerry) ***@***.***>:

**Comment by jerryuhoo** [comment]
Thanks for clarifying! Yeah, I think the arctan algorithm is probably not the best choice for the default. I have changed the default distortion algorithm in the latest release to cubic to avoid confusion.
